### ISSUE TITLE
Problem with boto3

### ISSUE THREAD

**Issue by Trulli99** [zubair-irshad/shapo#10]
Hi, when run the file net_train I get the following error: botocore.exceptions.NoCredentialsError: Unable to locate credentials
I would appreciate if you could help me.
Thank you!

**Comment by zubair-irshad** [comment]
Hi @Trulli99, 

Can you please share the full error trace? Also could you share the exact script you are trying to run?

**Comment by zubair-irshad** [comment]
Did you change your train and val paths to correct local locations [here](https://github.com/zubair-irshad/shapo/blob/master/configs/net_config.txt#L6)?

**Comment by Trulli99** [comment]
This is what I get in the workers file when I run the distributed_generate_data.py:
<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject

  0%|          | 0/45834 [00:00<?, ?it/s]
  0%|          | 0/45834 [00:01<?, ?it/s]
depth_full_path D:/shapo/data\camera_full_depths\train\00000\0000_composed.png
Traceback (most recent call last):
  File "prepare_data/distributed_worker.py", line 45, in <module>
    main(args)
  File "prepare_data/distributed_worker.py", line 22, in main
    annotate_camera_train(args.data_dir, args.start, args.end)
  File "D:\shapo\prepare_data\generate_training_data.py", line 253, in annotate_camera_train
    _DATASET.write(panoptic_datapoint)
  File "D:\shapo\simnet\lib\datapoint.py", line 248, in write
    self.s3.Bucket(self.bucket).put_object(Key=path, Body=buf)
  File "D:\shapo\env\lib\site-packages\boto3\resources\factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "D:\shapo\env\lib\site-packages\boto3\resources\action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "D:\shapo\env\lib\site-packages\botocore\client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "D:\shapo\env\lib\site-packages\botocore\client.py", line 943, in _make_api_call
    http, parsed_response = self._make_request(
  File "D:\shapo\env\lib\site-packages\botocore\client.py", line 966, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "D:\shapo\env\lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "D:\shapo\env\lib\site-packages\botocore\endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "D:\shapo\env\lib\site-packages\botocore\endpoint.py", line 134, in create_request
    self._event_emitter.emit(
  File "D:\shapo\env\lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "D:\shapo\env\lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "D:\shapo\env\lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "D:\shapo\env\lib\site-packages\botocore\signers.py", line 105, in handler
    return self.sign(operation_name, request)
  File "D:\shapo\env\lib\site-packages\botocore\signers.py", line 189, in sign
    auth.add_auth(request)
  File "D:\shapo\env\lib\site-packages\botocore\auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials

**Comment by zubair-irshad** [comment]
Hi @Trulli99, 

Did you change the _DATASET flag [here](https://github.com/zubair-irshad/shapo/blob/master/prepare_data/generate_training_data.py#L153)? Please change [this](https://github.com/zubair-irshad/shapo/blob/master/prepare_data/generate_training_data.py#L153) and all the respective _DATASET flags to the ones pointing to your local filepaths where you'd like to save your data. 

SImilarly for running net_train.py, change your train and val paths to correct local locations [here](https://github.com/zubair-irshad/shapo/blob/master/configs/net_config.txt#L6). Let me know if this is workable for you

**Comment by Trulli99** [comment]
Thank you, I will do that. Sorry to bother

**Comment by zubair-irshad** [comment]
Thanks, you could also pull the latest from master branch. Please see this [commit](https://github.com/zubair-irshad/shapo/commit/0d6d515e3420b126bdcb2cc9eaedabb5c182cb24). I have updated all data saving and loading paths and it should run out of the box.
